# Generated by Django 3.0.6 on 2020-05-06 12:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='wiki',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
