# Generated by Django 3.0.6 on 2020-05-07 01:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20200506_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('ENH', 'Enchancement'), ('U', 'UI/UX'), ('BUG', 'Bug'), ('BCP', 'Browser Compatibility Problem')], max_length=5)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('TBD', 'To-Be-Disscussed'), ('R', 'Resolved')], default='P', max_length=3)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='projects.Project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
