# Generated by Django 3.0.6 on 2020-05-07 01:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ENH', 'Enchancement'), ('U', 'UI/UX'), ('BUG', 'Bug'), ('BCP', 'Browser Compatibility Problem'), ('SEC', 'Security'), ('C', 'Crash')], max_length=3),
        ),
    ]
