# Generated by Django 3.0.6 on 2020-05-07 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_auto_20200507_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assigned At')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_you_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='projects.Issue')),
            ],
        ),
    ]
