# Generated by Django 3.0.6 on 2020-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enrolment_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
