# Generated by Django 3.0.6 on 2020-06-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20200626_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated At'),
        ),
    ]
