# Generated by Django 3.0.6 on 2020-06-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20200626_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_deployed',
            field=models.BooleanField(default=False),
        ),
    ]
