# Generated by Django 3.0.6 on 2020-07-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20200705_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.TextField(default='http://localhost:8000/images/guest-user.jpg'),
        ),
    ]
