# Generated by Django 3.0.6 on 2020-07-08 03:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200705_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
